// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package task

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

// ChangeRequestOptions configures provider API calls for PR/MR creation.
type ChangeRequestOptions struct {
	Token      string
	HTTPClient *http.Client
	APIBase    string
}

// ChangeRequest describes the provider API request needed to create a PR or MR.
type ChangeRequest struct {
	Provider string
	Method   string
	URL      string
	Headers  map[string]string
	Body     []byte
}

// ChangeRequestResult is the provider-neutral result of a PR/MR creation call.
type ChangeRequestResult struct {
	Provider string
	URL      string
}

// BuildChangeRequest builds a GitHub pull request or GitLab merge request call from a FactoryTask.
func BuildChangeRequest(task *FactoryTask, opts ChangeRequestOptions) (*ChangeRequest, error) {
	if task == nil {
		return nil, errors.New("FactoryTask is required")
	}
	if err := task.Validate(); err != nil {
		return nil, err
	}
	if !task.Spec.ChangeRequest.Enabled {
		return nil, errors.New("spec.changeRequest.enabled must be true")
	}
	changeBranch, targetBranch, _, _, _, _ := changeRequestDefaults(task)
	title := task.Spec.ChangeRequest.Title
	if title == "" {
		title = task.Spec.ChangeRequest.CommitMessage
	}
	if title == "" {
		title = fmt.Sprintf("Apply FactoryTask %s", task.Metadata.Name)
	}
	body := task.Spec.ChangeRequest.Body
	if body == "" {
		body = fmt.Sprintf("Generated by ai-factory for FactoryTask `%s`.", task.Metadata.Name)
	}

	switch task.Spec.Source.Provider {
	case ProviderGitHub:
		return buildGitHubPullRequest(task, opts, changeBranch, targetBranch, title, body)
	case ProviderGitLab:
		return buildGitLabMergeRequest(task, opts, changeBranch, targetBranch, title, body)
	default:
		return nil, fmt.Errorf("unsupported change request provider %q", task.Spec.Source.Provider)
	}
}

// CreateChangeRequest creates a GitHub pull request or GitLab merge request.
func CreateChangeRequest(ctx context.Context, task *FactoryTask, opts ChangeRequestOptions) (*ChangeRequestResult, error) {
	req, err := BuildChangeRequest(task, opts)
	if err != nil {
		return nil, err
	}
	httpReq, err := http.NewRequestWithContext(ctx, req.Method, req.URL, bytes.NewReader(req.Body))
	if err != nil {
		return nil, fmt.Errorf("create change request: %w", err)
	}
	for key, value := range req.Headers {
		httpReq.Header.Set(key, value)
	}
	client := opts.HTTPClient
	if client == nil {
		client = &http.Client{Timeout: 30 * time.Second}
	}
	resp, err := client.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("post %s change request: %w", req.Provider, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, fmt.Errorf("post %s change request: unexpected status %s", req.Provider, resp.Status)
	}
	resultURL, err := decodeChangeRequestURL(req.Provider, resp)
	if err != nil {
		return nil, err
	}
	return &ChangeRequestResult{Provider: req.Provider, URL: resultURL}, nil
}

func buildGitHubPullRequest(task *FactoryTask, opts ChangeRequestOptions, head, base, title, body string) (*ChangeRequest, error) {
	token := opts.Token
	if token == "" {
		token = os.Getenv("GITHUB_TOKEN")
	}
	if token == "" {
		return nil, errors.New("GITHUB_TOKEN is required to create GitHub pull requests")
	}
	apiBase := strings.TrimRight(opts.APIBase, "/")
	if apiBase == "" {
		apiBase = defaultGitHubAPIBase
	}
	payload, err := json.Marshal(map[string]string{
		"title": title,
		"body":  body,
		"head":  head,
		"base":  base,
	})
	if err != nil {
		return nil, fmt.Errorf("encode GitHub pull request: %w", err)
	}
	owner, repo, err := splitRepository(task.Spec.Source.Repository)
	if err != nil {
		return nil, err
	}
	return &ChangeRequest{
		Provider: ProviderGitHub,
		Method:   http.MethodPost,
		URL:      fmt.Sprintf("%s/repos/%s/%s/pulls", apiBase, url.PathEscape(owner), url.PathEscape(repo)),
		Headers: map[string]string{
			"Accept":        "application/vnd.github+json",
			"Authorization": "Bearer " + token,
			"Content-Type":  "application/json",
		},
		Body: payload,
	}, nil
}

func buildGitLabMergeRequest(task *FactoryTask, opts ChangeRequestOptions, sourceBranch, targetBranch, title, body string) (*ChangeRequest, error) {
	token := opts.Token
	if token == "" {
		token = os.Getenv("GITLAB_TOKEN")
	}
	if token == "" {
		return nil, errors.New("GITLAB_TOKEN is required to create GitLab merge requests")
	}
	apiBase := strings.TrimRight(opts.APIBase, "/")
	if apiBase == "" {
		host := task.Spec.Source.Host
		if host == "" {
			host = "gitlab.com"
		}
		apiBase = fmt.Sprintf("https://%s/api/v4", host)
	}
	payload, err := json.Marshal(map[string]string{
		"title":         title,
		"description":   body,
		"source_branch": sourceBranch,
		"target_branch": targetBranch,
	})
	if err != nil {
		return nil, fmt.Errorf("encode GitLab merge request: %w", err)
	}
	return &ChangeRequest{
		Provider: ProviderGitLab,
		Method:   http.MethodPost,
		URL:      fmt.Sprintf("%s/projects/%s/merge_requests", apiBase, url.PathEscape(task.Spec.Source.Repository)),
		Headers: map[string]string{
			"Content-Type":  "application/json",
			"PRIVATE-TOKEN": token,
		},
		Body: payload,
	}, nil
}

func decodeChangeRequestURL(provider string, resp *http.Response) (string, error) {
	var payload map[string]any
	if err := json.NewDecoder(resp.Body).Decode(&payload); err != nil {
		return "", fmt.Errorf("decode %s change request response: %w", provider, err)
	}
	for _, key := range []string{"html_url", "web_url"} {
		if value, ok := payload[key].(string); ok && value != "" {
			return value, nil
		}
	}
	return "", fmt.Errorf("%s change request response missing URL", provider)
}

func splitRepository(repository string) (string, string, error) {
	parts := strings.Split(repository, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		return "", "", fmt.Errorf("GitHub repository must look like owner/repo, got %q", repository)
	}
	return parts[0], parts[1], nil
}
