// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package task

import (
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestBuildGitHubPullRequest(t *testing.T) {
	task := mustChangeRequestTask(t, ProviderGitHub)
	req, err := BuildChangeRequest(task, ChangeRequestOptions{
		Token:   "token",
		APIBase: "https://api.github.test",
	})
	if err != nil {
		t.Fatalf("BuildChangeRequest() error = %v", err)
	}
	if req.URL != "https://api.github.test/repos/liyuerich/ai-factory/pulls" {
		t.Fatalf("url = %q", req.URL)
	}
	if req.Headers["Authorization"] != "Bearer token" {
		t.Fatalf("authorization = %q", req.Headers["Authorization"])
	}
	var payload map[string]string
	if err := json.Unmarshal(req.Body, &payload); err != nil {
		t.Fatalf("json.Unmarshal() error = %v", err)
	}
	if payload["head"] != "ai-factory/fix-docs" {
		t.Fatalf("head = %q", payload["head"])
	}
	if payload["base"] != "main" {
		t.Fatalf("base = %q", payload["base"])
	}
	if payload["title"] != "Fix docs" {
		t.Fatalf("title = %q", payload["title"])
	}
}

func TestBuildGitHubPullRequestUsesAuthTokenEnv(t *testing.T) {
	t.Setenv("AI_FACTORY_GITHUB_TOKEN", "env-token")
	task := mustChangeRequestTask(t, ProviderGitHub)
	task.Spec.ChangeRequest.AuthTokenEnv = "AI_FACTORY_GITHUB_TOKEN"
	req, err := BuildChangeRequest(task, ChangeRequestOptions{
		APIBase: "https://api.github.test",
	})
	if err != nil {
		t.Fatalf("BuildChangeRequest() error = %v", err)
	}
	if req.Headers["Authorization"] != "Bearer env-token" {
		t.Fatalf("authorization = %q", req.Headers["Authorization"])
	}
}

func TestBuildGitLabMergeRequest(t *testing.T) {
	task := mustChangeRequestTask(t, ProviderGitLab)
	req, err := BuildChangeRequest(task, ChangeRequestOptions{
		Token: "token",
	})
	if err != nil {
		t.Fatalf("BuildChangeRequest() error = %v", err)
	}
	if req.URL != "https://gitlab.example.com/api/v4/projects/platform%2Fai%2Fai-factory/merge_requests" {
		t.Fatalf("url = %q", req.URL)
	}
	if req.Headers["PRIVATE-TOKEN"] != "token" {
		t.Fatalf("private token = %q", req.Headers["PRIVATE-TOKEN"])
	}
	var payload map[string]string
	if err := json.Unmarshal(req.Body, &payload); err != nil {
		t.Fatalf("json.Unmarshal() error = %v", err)
	}
	if payload["source_branch"] != "ai-factory/fix-docs" {
		t.Fatalf("source_branch = %q", payload["source_branch"])
	}
	if payload["target_branch"] != "main" {
		t.Fatalf("target_branch = %q", payload["target_branch"])
	}
	if payload["description"] != "Generated by ai-factory." {
		t.Fatalf("description = %q", payload["description"])
	}
}

func TestCreateChangeRequest(t *testing.T) {
	var gotPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		w.WriteHeader(http.StatusCreated)
		_, _ = w.Write([]byte(`{"html_url":"https://github.com/liyuerich/ai-factory/pull/10"}`))
	}))
	defer server.Close()

	result, err := CreateChangeRequest(context.Background(), mustChangeRequestTask(t, ProviderGitHub), ChangeRequestOptions{
		Token:   "token",
		APIBase: server.URL,
	})
	if err != nil {
		t.Fatalf("CreateChangeRequest() error = %v", err)
	}
	if gotPath != "/repos/liyuerich/ai-factory/pulls" {
		t.Fatalf("path = %q", gotPath)
	}
	if result.URL != "https://github.com/liyuerich/ai-factory/pull/10" {
		t.Fatalf("result URL = %q", result.URL)
	}
}

func TestCreateChangeRequestTreatsGitHubAlreadyExistsAsSuccess(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusUnprocessableEntity)
		_, _ = w.Write([]byte(`{"message":"Validation Failed","errors":[{"message":"A pull request already exists for liyuerich:ai-factory/fix-docs."}]}`))
	}))
	defer server.Close()

	result, err := CreateChangeRequest(context.Background(), mustChangeRequestTask(t, ProviderGitHub), ChangeRequestOptions{
		Token:   "token",
		APIBase: server.URL,
	})
	if err != nil {
		t.Fatalf("CreateChangeRequest() error = %v", err)
	}
	if !result.AlreadyExists {
		t.Fatalf("AlreadyExists = false")
	}
}

func TestCreateChangeRequestClassifiesAuthFailure(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte(`{"message":"Resource not accessible by integration"}`))
	}))
	defer server.Close()

	_, err := CreateChangeRequest(context.Background(), mustChangeRequestTask(t, ProviderGitHub), ChangeRequestOptions{
		Token:   "token",
		APIBase: server.URL,
	})
	if err == nil {
		t.Fatal("CreateChangeRequest() error = nil, want auth error")
	}
	if !IsChangeRequestAuthError(err) {
		t.Fatalf("error = %v, want auth classification", err)
	}
}

func TestCreateChangeRequestTreatsGitLabAlreadyExistsAsSuccess(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusConflict)
		_, _ = w.Write([]byte(`{"message":["Another open merge request already exists for this source branch"]}`))
	}))
	defer server.Close()

	result, err := CreateChangeRequest(context.Background(), mustChangeRequestTask(t, ProviderGitLab), ChangeRequestOptions{
		Token:   "token",
		APIBase: server.URL,
	})
	if err != nil {
		t.Fatalf("CreateChangeRequest() error = %v", err)
	}
	if !result.AlreadyExists {
		t.Fatalf("AlreadyExists = false")
	}
}

func mustChangeRequestTask(t *testing.T, provider string) *FactoryTask {
	t.Helper()
	repository := "liyuerich/ai-factory"
	host := ""
	if provider == ProviderGitLab {
		repository = "platform/ai/ai-factory"
		host = "gitlab.example.com"
	}
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: fix-docs
spec:
  source:
    provider: ` + provider + `
    host: ` + host + `
    repository: ` + repository + `
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
    branchPrefix: ai-factory
    commitMessage: Fix docs
    title: Fix docs
    body: Generated by ai-factory.
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	return task
}
