// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package task

import (
	"encoding/json"
	"strings"
	"testing"
	"time"
)

func TestParseValidGitHubTask(t *testing.T) {
	data := []byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: validate-ai-factory
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    instructions: validate the factory-runtime-proxy spec
`)

	task, err := Parse(data)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if task.Spec.Source.Provider != ProviderGitHub {
		t.Fatalf("provider = %q, want %q", task.Spec.Source.Provider, ProviderGitHub)
	}
}

func TestParseValidGitLabTask(t *testing.T) {
	data := []byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: validate-gitlab-project
spec:
  source:
    provider: gitlab
    host: gitlab.example.com
    repository: platform/ai/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
`)

	task, err := Parse(data)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	if task.Spec.Source.Repository != "platform/ai/ai-factory" {
		t.Fatalf("repository = %q", task.Spec.Source.Repository)
	}
}

func TestParseRejectsUnsupportedProvider(t *testing.T) {
	data := []byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: bad-provider
spec:
  source:
    provider: bitbucket
    repository: team/repo
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    instructions: do something
`)

	_, err := Parse(data)
	if err == nil {
		t.Fatal("Parse() error = nil, want unsupported provider error")
	}
	if !strings.Contains(err.Error(), "spec.source.provider") {
		t.Fatalf("error = %v, want provider validation error", err)
	}
}

func TestCloneURLOrDefault(t *testing.T) {
	tests := []struct {
		name string
		src  SourceSpec
		want string
	}{
		{
			name: "github default host",
			src: SourceSpec{
				Provider:   ProviderGitHub,
				Repository: "liyuerich/ai-factory",
			},
			want: "https://github.com/liyuerich/ai-factory.git",
		},
		{
			name: "gitlab custom host",
			src: SourceSpec{
				Provider:   ProviderGitLab,
				Host:       "gitlab.example.com",
				Repository: "platform/ai/ai-factory",
			},
			want: "https://gitlab.example.com/platform/ai/ai-factory.git",
		},
		{
			name: "explicit clone url",
			src: SourceSpec{
				Provider:   ProviderGitLab,
				Repository: "platform/ai/ai-factory",
				CloneURL:   "https://mirror.example.com/ai-factory.git",
			},
			want: "https://mirror.example.com/ai-factory.git",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.src.CloneURLOrDefault()
			if err != nil {
				t.Fatalf("CloneURLOrDefault() error = %v", err)
			}
			if got != tt.want {
				t.Fatalf("CloneURLOrDefault() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestBuildExecutionPlan(t *testing.T) {
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: validate-gitlab-project
spec:
  source:
    provider: gitlab
    host: gitlab.example.com
    repository: platform/ai/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	plan, err := BuildExecutionPlan(task)
	if err != nil {
		t.Fatalf("BuildExecutionPlan() error = %v", err)
	}
	if plan.CloneURL != "https://gitlab.example.com/platform/ai/ai-factory.git" {
		t.Fatalf("CloneURL = %q", plan.CloneURL)
	}
	if plan.SandboxClaim != "validate-gitlab-project-claim" {
		t.Fatalf("SandboxClaim = %q", plan.SandboxClaim)
	}
	if got, want := len(plan.Steps), 3; got != want {
		t.Fatalf("len(Steps) = %d, want %d", got, want)
	}
}

func TestBuildExecutionPlanWithChangeRequest(t *testing.T) {
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: fix-docs
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
    branchPrefix: ai-factory
    commitMessage: fix docs from task
    title: Fix docs
    body: Generated by ai-factory.
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	plan, err := BuildExecutionPlan(task)
	if err != nil {
		t.Fatalf("BuildExecutionPlan() error = %v", err)
	}
	if plan.ChangeBranch != "ai-factory/fix-docs" {
		t.Fatalf("ChangeBranch = %q", plan.ChangeBranch)
	}
	if plan.TargetBranch != "main" {
		t.Fatalf("TargetBranch = %q", plan.TargetBranch)
	}
	if plan.GitAuthTokenEnv != "GITHUB_TOKEN" {
		t.Fatalf("GitAuthTokenEnv = %q", plan.GitAuthTokenEnv)
	}
	if got, want := len(plan.Steps), 7; got != want {
		t.Fatalf("len(Steps) = %d, want %d", got, want)
	}
	names := make([]string, 0, len(plan.Steps))
	for _, step := range plan.Steps {
		names = append(names, step.Name)
	}
	wantNames := []string{"configure git credentials", "clone repository", "checkout base ref", "create change branch", "run command 1", "commit changes", "push change branch"}
	if strings.Join(names, ",") != strings.Join(wantNames, ",") {
		t.Fatalf("step names = %#v", names)
	}
	authCommand := strings.Join(plan.Steps[0].Command, " ")
	if !strings.Contains(authCommand, "GITHUB_TOKEN is required in the sandbox environment for git clone/push") {
		t.Fatalf("auth command = %#v", plan.Steps[0].Command)
	}
	commitStep := plan.Steps[5]
	commitCommand := strings.Join(commitStep.Command, " ")
	if !strings.Contains(commitCommand, "git -c user.name='ai-factory' -c user.email='ai-factory@example.invalid' commit -m 'fix docs from task'") {
		t.Fatalf("commit command = %#v", commitStep.Command)
	}
}

func TestBuildExecutionPlanWithGitLabChangeRequestAuthDefaults(t *testing.T) {
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: fix-docs
spec:
  source:
    provider: gitlab
    host: gitlab.example.com
    repository: platform/ai/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	plan, err := BuildExecutionPlan(task)
	if err != nil {
		t.Fatalf("BuildExecutionPlan() error = %v", err)
	}
	if plan.GitAuthTokenEnv != "GITLAB_TOKEN" {
		t.Fatalf("GitAuthTokenEnv = %q", plan.GitAuthTokenEnv)
	}
	if plan.GitAuthUsername != "oauth2" {
		t.Fatalf("GitAuthUsername = %q", plan.GitAuthUsername)
	}
	authCommand := strings.Join(plan.Steps[0].Command, " ")
	if !strings.Contains(authCommand, "credential.https://gitlab.example.com.helper") {
		t.Fatalf("auth command = %#v", plan.Steps[0].Command)
	}
}

func TestParseRejectsConflictingChangeRequestBranchFields(t *testing.T) {
	_, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: bad-change-request
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
    branchName: explicit
    branchPrefix: prefix
`))
	if err == nil {
		t.Fatal("Parse() error = nil, want conflicting branch validation error")
	}
	if !strings.Contains(err.Error(), "spec.changeRequest.branchName") {
		t.Fatalf("error = %v, want changeRequest validation error", err)
	}
}

func TestParseRejectsInvalidChangeRequestAuthTokenEnv(t *testing.T) {
	_, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: bad-change-request-auth
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
    authTokenEnv: 1BAD
`))
	if err == nil {
		t.Fatal("Parse() error = nil, want authTokenEnv validation error")
	}
	if !strings.Contains(err.Error(), "spec.changeRequest.authTokenEnv") {
		t.Fatalf("error = %v, want authTokenEnv validation error", err)
	}
}

func TestReconcileBuildsSandboxClaim(t *testing.T) {
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: Validate GitHub Project
  namespace: factory-system
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
  work:
    commands:
    - go test ./...
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	output, err := Reconcile(task)
	if err != nil {
		t.Fatalf("Reconcile() error = %v", err)
	}
	if output.SandboxClaim.APIVersion != sandboxClaimAPIVersion {
		t.Fatalf("APIVersion = %q", output.SandboxClaim.APIVersion)
	}
	if output.SandboxClaim.Metadata.Name != "validate-github-project-claim" {
		t.Fatalf("claim name = %q", output.SandboxClaim.Metadata.Name)
	}
	if output.SandboxClaim.Metadata.Namespace != "factory-system" {
		t.Fatalf("namespace = %q", output.SandboxClaim.Metadata.Namespace)
	}
	if got := output.SandboxClaim.Metadata.Labels[taskNameLabel]; got != "validate-github-project" {
		t.Fatalf("task label = %q", got)
	}

	data, err := output.SandboxClaimYAML()
	if err != nil {
		t.Fatalf("SandboxClaimYAML() error = %v", err)
	}
	if !strings.Contains(string(data), "kind: SandboxClaim") {
		t.Fatalf("SandboxClaimYAML() = %s", data)
	}
}

func TestReconcileInjectsGitAuthTokenEnv(t *testing.T) {
	t.Setenv("GITHUB_TOKEN", "test-token")
	task, err := Parse([]byte(`
apiVersion: factory.ai.gke.io/v1alpha1
kind: FactoryTask
metadata:
  name: fix-docs
  namespace: factory-system
spec:
  source:
    provider: github
    repository: liyuerich/ai-factory
    baseRef: main
  agent:
    name: builder
  sandbox:
    templateRef: go-dev
    containerName: dev
  work:
    commands:
    - go test ./...
  changeRequest:
    enabled: true
`))
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	output, err := Reconcile(task)
	if err != nil {
		t.Fatalf("Reconcile() error = %v", err)
	}
	envs, ok := output.SandboxClaim.Spec["env"].([]interface{})
	if !ok || len(envs) != 1 {
		t.Fatalf("env = %#v", output.SandboxClaim.Spec["env"])
	}
	env, ok := envs[0].(map[string]interface{})
	if !ok {
		t.Fatalf("env[0] = %#v", envs[0])
	}
	if env["name"] != "GITHUB_TOKEN" || env["value"] != "test-token" || env["containerName"] != "dev" {
		t.Fatalf("env[0] = %#v", env)
	}
}

func TestStatusMergePatch(t *testing.T) {
	patch, err := StatusMergePatch(StatusPatchOptions{
		Phase:            PhaseRunning,
		Message:          "executing generated plan",
		Reason:           "RunOnceStarted",
		SandboxClaimName: "validate-claim",
		SandboxName:      "validate-sandbox",
		Now:              time.Date(2026, 6, 30, 1, 2, 3, 0, time.UTC),
	})
	if err != nil {
		t.Fatalf("StatusMergePatch() error = %v", err)
	}

	var got struct {
		Status FactoryTaskStatus `json:"status"`
	}
	if err := json.Unmarshal(patch, &got); err != nil {
		t.Fatalf("json.Unmarshal() error = %v", err)
	}
	if got.Status.Phase != PhaseRunning {
		t.Fatalf("phase = %q", got.Status.Phase)
	}
	if got.Status.StartedAt != "2026-06-30T01:02:03Z" {
		t.Fatalf("startedAt = %q", got.Status.StartedAt)
	}
	if got.Status.CompletedAt != "" {
		t.Fatalf("completedAt = %q, want empty for running phase", got.Status.CompletedAt)
	}
	if len(got.Status.Conditions) != 1 {
		t.Fatalf("conditions length = %d", len(got.Status.Conditions))
	}
	if got.Status.Conditions[0].Reason != "RunOnceStarted" {
		t.Fatalf("condition reason = %q", got.Status.Conditions[0].Reason)
	}
}
